In [ ]:
!pip install --upgrade pip
!pip install --upgrade scikit-learn==0.23.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 2.1 MB 5.4 MB/s 
  Attempting uninstall: pip
    Found existing installation: pip 21.1.3
    Uninstalling pip-21.1.3:
      Successfully uninstalled pip-21.1.3
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 45.2 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.0.2
    Uninstalling scikit-learn-1.0.2:
      Successfully uninstalled scikit-learn-1.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yellowbrick 1.4 requires scikit-learn>=1.0.0, but you have scikit-learn 0.23.0 which is incompatible.
imbalanced-learn 0.8.1 requires scikit-learn>=0.24, but you have sciki

In [ ]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
from keras.datasets import mnist
(X_train, y_train), (X_pred, y_pred) = mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [ ]:
X_train = X_train[:3000]
y_train = y_train[:3000]

In [ ]:
len(y_train)

3000

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.3, random_state=22)

In [ ]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.ensemble import RandomForestClassifier

In [ ]:
dim = 784 # 28*28 
X_train = X_train.reshape(len(X_train), dim)
X_test = X_test.reshape(len(X_test), dim)

In [ ]:
tree = RandomForestClassifier(criterion='gini', min_samples_leaf=10, max_depth=20, n_estimators=10, random_state=22)
clf = OneVsRestClassifier(tree).fit(X_train, y_train)

In [ ]:
y_pred = clf.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix
CM = confusion_matrix(y_test, y_pred)

In [ ]:
CM

array([[ 74,   0,   0,   1,   0,   0,   2,   0,   1,   0],
       [  0, 119,   0,   1,   0,   1,   1,   1,   1,   0],
       [  0,   1,  74,   2,   0,   0,   3,   2,   1,   2],
       [  1,   2,   4,  73,   0,   3,   0,   0,   0,   4],
       [  1,   2,   1,   0,  82,   2,   1,   0,   0,   4],
       [  1,   0,   1,   7,   2,  68,   2,   0,   1,   2],
       [  1,   1,   3,   0,   1,   2,  77,   0,   0,   0],
       [  0,   4,   3,   0,   2,   0,   0,  93,   0,   3],
       [  0,   6,   1,   5,   0,   2,   1,   0,  70,   1],
       [  1,   0,   0,   3,   3,   0,   0,   5,   0,  61]])

In [ ]:
CM[0][0] + CM[1][1] + CM[2][2] + CM[3][3] + CM[4][4] + CM[5][5] + CM[6][6] + CM[7][7] + CM[8][8] + CM[9][9]

791

In [ ]:
import pandas as pd
df = pd.read_csv('/DataForPrediction_FinalTask.csv') 

In [ ]:
df.head(83)

id  f0  f1  f2  f3  f4  f5  f6  f7  f8  ...  f774  f775  f776  f777  f778  \
0    0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0     0   
1    1   0   0   0   0   0   0   0   0   0  ...     0     0     0     0     0   
2    2   0   0   0   0   0   0   0   0   0  ...     0     0     0     0     0   
3    3   0   0   0   0   0   0   0   0   0  ...     0     0     0     0     0   
4    4   0   0   0   0   0   0   0   0   0  ...     0     0     0     0     0   
..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...   ...   ...   ...   ...   ...   
78  78   0   0   0   0   0   0   0   0   0  ...     0     0     0     0     0   
79  79   0   0   0   0   0   0   0   0   0  ...     0     0     0     0     0   
80  80   0   0   0   0   0   0   0   0   0  ...     0     0     0     0     0   
81  81   0   0   0   0   0   0   0   0   0  ...     0     0     0     0     0   
82  82   0   0   0   0   0   0   0   0   0  ...     0     0     0     0     0   

    f779  f780  f781  f782  f783  
0      0     0     0     0     0  
1      0     0     0     0     0  
2      0     0     0     0     0  
3      0     0     0     0     0  
4      0     0     0     0     0  
..   ...   ...   ...   ...   ...  
78     0     0     0     0     0  
79     0     0     0     0     0  
80     0     0     0     0     0  
81     0     0     0     0     0  
82     0     0     0     0     0  

[83 rows x 785 columns]

In [ ]:
features = list(df.columns[1:785])

In [ ]:
features

In [ ]:
df.loc[82, features]

f0      0
f1      0
f2      0
f3      0
f4      0
       ..
f779    0
f780    0
f781    0
f782    0
f783    0
Name: 82, Length: 784, dtype: int64

In [ ]:
clf.predict([df.loc[82, features].tolist()])[0]

2

In [ ]:
clf.predict_proba([df.loc[82, features].tolist()])[0][2]

0.7451723956998251

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=32, svd_solver='full')
modelPCA = pca.fit(X_train) 

X_train_pca32 = modelPCA.transform(X_train)

In [ ]:
explained_variance = np.round(np.cumsum(pca.explained_variance_ratio_),3)
explained_variance

array([0.097, 0.171, 0.236, 0.293, 0.341, 0.386, 0.418, 0.447, 0.476,
       0.499, 0.52 , 0.541, 0.558, 0.574, 0.591, 0.607, 0.619, 0.632,
       0.644, 0.655, 0.666, 0.676, 0.686, 0.695, 0.704, 0.712, 0.72 ,
       0.728, 0.735, 0.742, 0.749, 0.755])

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dec_tree = DecisionTreeClassifier(criterion='gini', #splitting criterion
                              min_samples_leaf=10, #minimum number of samples per leaf
                              max_depth=20, #maximum number of leaves
                              random_state=22)
dec_clf = OneVsRestClassifier(dec_tree).fit(X_train_pca32, y_train)

In [ ]:
X_test_pca32 = modelPCA.transform(X_test)

In [ ]:
y_pred_pca32 = dec_clf.predict(X_test_pca32)

In [ ]:
from sklearn.metrics import confusion_matrix
CM = confusion_matrix(y_test, y_pred_pca32)

In [ ]:
CM

array([[ 69,   0,   1,   2,   0,   2,   2,   0,   0,   2],
       [  0, 117,   0,   1,   0,   0,   1,   1,   2,   2],
       [  3,   1,  53,  10,   2,   1,   3,   2,   6,   4],
       [  2,   0,   6,  65,   0,   4,   1,   1,   1,   7],
       [  1,   1,   3,   1,  65,   6,   5,   1,   3,   7],
       [  2,   1,   2,  17,   3,  41,   3,   1,   4,  10],
       [  1,   1,   1,   1,   1,   2,  75,   0,   1,   2],
       [  1,   3,   2,   1,   9,   1,   0,  82,   0,   6],
       [  2,   1,   5,   6,   0,   6,   1,   0,  55,  10],
       [  2,   0,   0,   0,   8,   4,   0,  11,   3,  45]])

In [ ]:
CM[0][0] + CM[1][1] + CM[2][2] + CM[3][3] + CM[4][4] + CM[5][5] + CM[6][6] + CM[7][7] + CM[8][8] + CM[9][9]

667

In [ ]:
X_train_custom = df.drop('id', axis=1)

In [ ]:
X_train_custom_pca32 = modelPCA.transform(X_train_custom.to_numpy())

In [ ]:
dec_clf.predict_proba([list(X_train_custom_pca32[82].reshape(1, -1)[0])])

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]])